#!/usr/bin/env bash

set -x

SECOR=/opt/secor

# ProgressMonitorMain
# LogFilePrinterMain
CLASS_NAME=com.pinterest.secor.main.${1:-ConsumerMain}
shift

exec java -ea \
     -Dsecor_group=secor0 \
     -Dlog4j.configuration=file://"$SECOR"/log4j.prod.properties \
     -Dconfig=file://"$SECOR"/secor.properties \
     -cp .:"$SECOR"/*:"$SECOR"/lib/* \
     "$CLASS_NAME" "$@"
